### ISSUE TITLE
Improve user experience in form submission

### ISSUE THREAD

**Issue by Ahd-Kabeer-Hadi** [mirrorfolio/menteor1#27]
### Issue Description:
We currently have a little lag to the success page after processing the data to backend, so we need to optimize the user experience here, you can improve the BE call performance here, this issue is simple one and i was about to take it in my care. since we got a some interested people in our previous issue i thought I shoud give you guys a shot
### Before starting development, please follow these steps:

1. Create a branch on your local machine with the name of the token.
2. Ensure that you're working on this branch for the duration of the development process.

#### Best Practices for Open Source Contribution:

1. **Read the Contribution Guidelines:** Familiarise yourself with the project's contribution guidelines. These guidelines usually outline how to contribute, coding standards, and other important information.

2. **Understand the Project:** Take the time to understand the project's goals, architecture, and existing codebase before making any contributions. This ensures that your contributions align with the project's objectives.

3. **Follow Coding Standards:** Adhere to the coding style and standards established by the project. Consistent coding style makes it easier for others to read and maintain the code.

4. **Document Your Code:** Provide clear and concise comments within your code to explain its purpose, functionality, and any important considerations. Good documentation makes it easier for other developers to understand and use your code.

5. **Test Your Changes:** Thoroughly test your changes to ensure they work as intended and do not introduce any regressions. Write unit tests whenever possible to automate the testing process and increase confidence in your changes.

6. **Keep Your Pull Requests Small and Focused:** Break your changes into smaller, focused pull requests rather than large, monolithic ones. This makes it easier for maintainers to review your code and for other contributors to understand the changes.

7. **Be Responsive to Feedback:** Be open to feedback and constructive criticism from maintainers and other contributors. Address any feedback promptly and be willing to make necessary adjustments to your code.

8. **Be Patient and Respectful:** Open source projects often have diverse communities with different perspectives and priorities. Be patient and respectful when discussing ideas or providing feedback, and always assume good intentions from other contributors.

9. **Contribute Positively:** Contribute to a positive and inclusive community by being supportive of others, encouraging collaboration, and fostering a welcoming environment for all contributors.

10. **Celebrate Your Contributions:** Your contributions, no matter how small, are valuable to the project. Celebrate your achievements and the contributions of others to build a positive and thriving open source community.

**Comment by Ahd-Kabeer-Hadi** [comment]
@nithin6x9 @itsOmSarraf guys please check this out, the first best solution will get merged to into prod

**Comment by nithin6x9** [comment]
Sure i'll  work on this!

**Comment by Ahd-Kabeer-Hadi** [comment]
@nithin6x9 are you still doing it? need any help?

**Comment by nithin6x9** [comment]
I tried to find the solution but unfortunately i couldn't
